
export const react = ['react', 'react-scripts'];

export const dsComp = [
    'nav-frontend-chevron',
    'nav-frontend-ekspanderbartpanel',
    'nav-frontend-skjema',
    'nav-frontend-knapper',
    'nav-frontend-alertstriper',
    'nav-frontend-js-utils',
    'nav-frontend-core',
    'nav-frontend-etiketter',
    'nav-frontend-hjelpetekst',
    'nav-frontend-ikonknapper',
    'nav-frontend-ikoner-assets',
    'nav-frontend-lenker',
    'nav-frontend-lenkepanel',
    'nav-frontend-lermerpanel',
    'nav-frontend-lukknapp',
    'nav-frontend-modal',
    'nav-frontend-panel',
    'nav-frontend-popover',
    'nav-frontend-snakkeboble',
    'nav-frontend-spinner',
    'nav-frontend-stegindikator',
    'nav-frontend-tabell-style',
    'nav-frontend-tabs',
    'nav-frontend-tekstomrade',
    'nav-frontend-toggle',
    'nav-frontend-typografi',
    'nav-frontend-veileder',
    'nav-frontend-veilederpanel',
    'nav-frontend-js-utils',
    'nav-frontend-core'
];

export const dsCompStyles = [
    'nav-frontend-chevron-style',
    'nav-frontend-ekspanderbartpanel-style',
    'nav-frontend-skjema-style',
    'nav-frontend-knapper-style',
    'nav-frontend-alertstriper-style',
    'nav-frontend-etiketter-style',
    'nav-frontend-hjelpetekst-style',
    'nav-frontend-ikonknapper-style',
    'nav-frontend-ikoner-assets',
    'nav-frontend-lenker-style',
    'nav-frontend-lenkepanel-style',
    'nav-frontend-lermerpanel-style',
    'nav-frontend-lukknapp-style',
    'nav-frontend-modal-style',
    'nav-frontend-panel-style',
    'nav-frontend-popover-style',
    'nav-frontend-snakkeboble-style',
    'nav-frontend-spinner-style',
    'nav-frontend-stegindikator-style',
    'nav-frontend-tabell-style-style',
    'nav-frontend-tabs-style',
    'nav-frontend-tekstomrade-style',
    'nav-frontend-toggle-style',
    'nav-frontend-typografi-style',
    'nav-frontend-veileder-style',
    'nav-frontend-veilederpanel-style'
];
